# Generated by Django 6.0.4 on 2026-04-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(help_text='Repo-relative path using forward slashes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(help_text='Absolute path on server disk where repo is stored.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(help_text='Qualified name (e.g. Class.method or func).', max_length=512)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('original_code', models.TextField()),
                ('optimized_code', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='optimizer.repofile')),
            ],
            options={
                'unique_together': {('file', 'function_name', 'start_line', 'end_line')},
            },
        ),
        migrations.AddField(
            model_name='repofile',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='optimizer.repository'),
        ),
        migrations.CreateModel(
            name='ProfilingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('original', 'original'), ('optimized', 'optimized')], max_length=16)),
                ('memory_usage', models.JSONField(blank=True, default=list)),
                ('peak_memory', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_results', to='optimizer.function')),
            ],
            options={
                'indexes': [models.Index(fields=['function', 'version'], name='optimizer_p_functio_c0bc8c_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='repofile',
            unique_together={('repo', 'file_path')},
        ),
    ]
