# Generated by Django 6.0.4 on 2026-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='decision',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='function',
            name='preferred_version',
            field=models.CharField(choices=[('original', 'original'), ('optimized', 'optimized')], default='original', max_length=16),
        ),
    ]
