# Generated by Django 6.0.4 on 2026-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_function_decision_function_preferred_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingresult',
            name='profiler_output',
            field=models.TextField(blank=True, default='', help_text='Raw memory_profiler text output (best-effort).'),
        ),
    ]
